fine_tune_type: lora
num_layers: 8
lora_parameters:
  rank: 4
  dropout: 0.0
  scale: 20.0
optimizer: adam
learning_rate: 0.0001
batch_size: 1
mask_prompt: true
max_seq_length: 256
steps_per_report: 1
steps_per_eval: 1000
val_batches: 1
seed: 230923
